apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finances.fullname" . }}-secrets
  labels:
    {{- include "finances.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.databaseUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
