apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finances.frontend.fullname" . }}
  labels:
    {{- include "finances.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "finances.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "finances.frontend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "finances.frontend.serviceAccountName" . }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          {{- if .Values.frontend.config }}
          envFrom:
            - configMapRef:
                name: {{ include "finances.frontend.fullname" . }}-config
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
