server:
  port: 8080

spring:
  application:
    name: personal-finances-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/finances
    username: finances
    password: finances
    default-schema: ${SPRING_DATASOURCE_DEFAULT_SCHEMA:public}
  jooq:
    sql-dialect: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${SPRING_DATASOURCE_DEFAULT_SCHEMA:public}

logging:
  level:
    sun.rmi.transport.tcp: OFF
  docker:
    compose:
      lifecycle-management: start-only

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
